'''constants used throughout the program'''
SAMPLE_RATE = 44100
LOWEST_FREQUENCY = 20
HIGH_SAMPLES = SAMPLE_RATE / LOWEST_FREQUENCY
DEVICE = 1
FREQUENCY_OVERLAP = 5
BLUETOOTH_SAMPLES = 160
FEEDBACK_NOISE_THRESH = 7
SLOW_FACTOR = 3
FAST_FACTOR = 4.5
HISS_THRESH = 15
